export const skillData=[
  {
    label:'FRONT END',
    data:[
      {
        skillname:'HTML5',
        percentage:'90',
      },
      {
        skillname:'css3',
        percentage:'80',
      },
      {
        skillname:'Javascript',
        percentage:'70',
      },
      {
        skillname:'ReactJs',
        percentage:'75',
      },
      {
        skillname:'Bootstrap',
        percentage:'90',
      },
      {
        skillname:'Typescript',
        percentage:'50',
      }
    ]
  },
{  
  label:'BACK END',
  data:[
    {
      skillname:'C#',
      percentage:'20'
    },
    {
      skillname:'Node JS',
      percentage:'30'
    }
  ]
},
 {
  label:'Database',
 data:[
  {
    skillname:'SQL',
    percentage:'40'
  },
  {
    skillname:'MongoDB',
    percentage:'30'
  }
 ]
 }
]